### ISSUE TITLE
error upgrading mod_via to version 2024030101

### ISSUE THREAD

**Issue by lcaylat** [SVIeSolutions/moodle-mod_via#9]
Hi,

When I try to update the mod_via plugin with the latest version available on Moodle plugins directory, I get an error:
![image](https://github.com/SVIeSolutions/moodle-mod_via/assets/65226314/63002fb5-a761-4078-8287-1c3f86c5b724)

I tested on Moodle 4.1.9 and on Moodle 4.3.3.

An idea ?

**Comment by kecherou** [comment]
Hi,
Same problem for us, even after the fix of yesterday.
<img width="1231" alt="Capture d’écran 2024-03-08 à 09 51 51" src="https://github.com/SVIeSolutions/moodle-mod_via/assets/18518025/2bbf4e91-4452-4969-82cc-9077f04d0f8e">
Tested on Moodle 4.2.6.

**Comment by lcaylat** [comment]
I no longer reproduce the problem with version 2024030602.
I am therefore closing the ticket.
